config/routes.rb
Rails.application.routes.draw do
  resources :competitions do
    collection do 
      get "search"
    end
    member do
      post "remove_tag", as: "remove_tag_from"
      post "add_tag", as: "add_tag_to"
    end
  end
  resources :competition_tags
  get "/about", to: "competitions#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "competitions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_and_belongs_to_many :competition_tags
  accepts_nested_attributes_for :competition_tags

  #Scopes
  scope :text_search, -> (search){ where("name LIKE ?", "%#{search}%").or(where("description LIKE ?", "%#{search}%")).or(where("topic LIKE ?", "%#{search}%"))}
  scope :valid_age, -> (age){ where("? >= age_from ", age).and(where("? <= age_to", age))}
  #scope :tag_search, -> (tag, competition){ where("#{competition.competition_tag_id} LIKE ?", tag) }

  def possible_new_competition_tags
    CompetitionTag.all #- competition_tags
  end
end

app/models/competition_tag.rb
class CompetitionTag < ApplicationRecord
  has_and_belongs_to_many :competitions

  #scope :tag_search, -> (tag){ where("id LIKE ?", tag) }
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: %i[ show edit update destroy remove_tag add_tag]

  # GET /competitions or /competitions.json
  def index
    @competitions = Competition.all
  end

  def search
    @search = params["query"]
    @age = params["age"].to_i
    @tags = params["tags"]
    @competitions = Competition.all
    @competitions = @competitions.text_search(@search) if @search
    @competitions = @competitions.valid_age(@age) if @age > 0
    if @tags != nil and @tags != [""] and @tags != []
      @competitions = @competitions.joins(:competition_tags).where(competition_tags: { id: @tags.filter{|tag| tag != ""} }).distinct
    end

  end

  def about
  end

  # GET /competitions/1 or /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions or /competitions.json
  def create
    @competition = Competition.new(competition_params)
    respond_to do |format|
      if @competition.save
        format.html { redirect_to competition_url(@competition), notice: "Competition was successfully created." }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1 or /competitions/1.json
  def update
    puts "======================================="
    puts competition_params
    puts "======================================="
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to competition_url(@competition), notice: "Competition was successfully updated." }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1 or /competitions/1.json
  def destroy
    @competition.destroy!

    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "Competition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def remove_tag
    tag = CompetitionTag.find(params[:competition_tag_id])
    @competition.competition_tags -= [tag]
    redirect_to @competition, notice: "Tag was successfully removed."
  end

  def add_tag
    tag = CompetitionTag.find(params[:competition_tag_id])
    @competition.competition_tags << tag
    redirect_to @competition, notice: "Tag was successfully added."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def competition_params
      params.require(:competition).permit(:name, :description, :topic, :age_from, :age_to, competition_tag_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_competition.html.erb
<div id="<%= dom_id competition %>">

  <br>

  <strong><%= competition.name %></strong>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= competition.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Topic:</strong>
    <%= competition.topic %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Age from:</strong>
    <%= competition.age_from %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Age to:</strong>
    <%= competition.age_to %>
  </p>
  <p>
    Tags:
    <% competition.competition_tags.each do |tag| %>
          <tr>
            <td><%= link_to tag.tag, search_competitions_path(tags: [tag]), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"%>
            <%# "," if %>
            </td>
          </tr>
        <% end %>
  </p>
  <br>
  </div>

app/views/competitions/_form.html.erb
<%= form_with(model: competition, class: "contents") do |form| %>
  <% if competition.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
        <% competition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :topic %>
    <%= form.text_field :topic, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :age_from %>
    <%= form.number_field :age_from, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :age_to %>
    <%= form.number_field :age_to, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <p>
    Tags: <%= form.collection_select :competition_tag_ids, competition.possible_new_competition_tags, :id, :tag, {include_blank: true, multiple: true} %>

  </p>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/competitions/about.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% %>

  <% content_for :title, "About us" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">About us</h1>
  </div>
    
  
  <br>
</div>

app/views/competitions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing competition</h1>

  <%= render "form", competition: @competition %>

  <%= link_to "Show this competition", @competition, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to competitions", competitions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/competitions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% %>

  <% content_for :title, "Competitions" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Competitions</h1>
    <%= link_to "New competition", new_competition_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <br>
  <div id="competitions" class="min-w-full">
    <% @competitions.each do |competition| %>
      <%= render competition %>
      <p>
        <%= link_to "Show this competition", competition, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
      <br>
    <% end %>
  </div>
</div>

app/views/competitions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New competition</h1>

  <%= render "form", competition: @competition %>

  <%= link_to "Back to competitions", competitions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/competitions/search.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Competitions" %>

  <h3>

    <strong>Search parameters </strong>

    <%if @search != nil and @search != ""%>
      <br>
      Text search: <%= @search %>
    <%end%>

  <%if @age != nil and @age.to_i > 0%>
      <br>
      Age: <%= @age %>
    <%end%>

    <% tags = @tags %>
    <%if tags != [""] and tags != nil and tags != []%>
    
      <% temp = [] %>
      <% tags.each do |tag|%> 
        <%temp << CompetitionTag.find_by(id: tag)%>
      <%end%>
      <br>
      Tags:
      <%temp.each do |tag| %>
          <tr>
            <td><%= link_to tag.tag, search_competitions_path(tags: [tag]), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" if tag != nil%>
            </td>
          </tr>
        <% end %>
    <%end%>

  </h3>

  <%= form_with method: :get do |form|%>
    <%# form.label :query, "Search for:"%>
    <%# form.text_field :query%>

  <div class="my-5">
    <%= form.label "Text search" %>
    <%= form.text_field :query, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :age %>
    <%= form.number_field :age, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :tags %>
    <%= form.collection_select :tags, CompetitionTag.all, :id, :tag, {multiple: true}, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>

  </div>

    <div class="inline">
    <%= form.submit "Search", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  
  </div>
  <% end %>

  <div class="flex justify-between items-center mt-5">
    <h1 class="font-bold text-4xl">Competitions</h1>
    <%= link_to "New competition", new_competition_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    
  </div>

  <div id="competitions" class="min-w-full mb-5">
    <% @competitions.each do |competition| %>
      <%= render competition %>
      <p>
        <%= link_to "Show this competition", competition, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
    <%if @competitions.empty?%>
      No results
    <%end%>
  </div>
  <%#@age%>
</div>

app/views/competitions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @competition %>

    <%= link_to "Edit this competition", edit_competition_path(@competition), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to competitions", competitions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this competition", @competition, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ATHENA Database</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class = "flex px-5">
      <hr>
      <div class = "px-5"><%=link_to "ATHENA", root_path%></div>
      <div class = "px-5">|</div>  
      <div class = "px-5"><%=link_to "Search",  search_competitions_path%> </div>
      <div class = "px-5">|</div>
      <div class = "px-5"><%=link_to "About",  about_path%></div>
      <hr>
      
    </div>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>